# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losers', '0006_auto_20150916_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
